@startuml Pacman 

class Personaje{
    + MoveLeft()
    + MoveRight()
    + MoverUp()
    + MoverDown()
}


class Fantasma{
    +MoveLeft
    +MoverDown
    +MoveRight
    +MoverUp
}
class Vida
class Puntuacion
class ObjetoComible
class Jugador

 Jugador "1" --* "1" Personaje 
 Pacman "1" --|> "1..*" Personaje
 Fantasma "1" --|> "1..*" Personaje
 Pacman "1" --* "1..*" ObjetoComible
 Jugador "1" --o "1" Pacman
 Jugador "1" --* "1..*" Puntuacion
 Jugador "1" --* "1..*" Vida
 @enduml