@startuml Pacman 

class Personaje{
    + MoveLeft()
    + MoveRight()
    + MoverUp()
    + MoverDown()
}


class Fantasma{
    +MoveLeft
    +MoverDown
    +MoveRight
    +MoverUp
}

class Puntuacion
class Comestible
class PantallaInicio
class Colisionable
class Juego

 Jugador "1" --* "1" Personaje 
 Pacman "1" --|> "1..*" Personaje
 Fantasma "1" --|> "1..*" Colisionable
 Personaje "1" --* "4.." Comestible
 Jugador "1" --o "1" Pacman
 Jugador "1" --* "1..*" Puntuacion
 Jugador "1" --* "1..*" Vida
Juego "1" --o "1" PantallaInicio
 @enduml